# Generated by Django 3.1.3 on 2023-06-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True)),
                ('nacionalidad', models.TextField(blank=True)),
                ('posicion', models.TextField(blank=True)),
                ('club', models.TextField(blank=True)),
                ('goles', models.IntegerField()),
                ('edad', models.IntegerField()),
                ('estatura', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('asistencias', models.IntegerField()),
                ('imagen', models.TextField(blank=True)),
            ],
        ),
    ]
